import Image from "next/image";
import Link from "next/link";
import { useSession, signIn, signOut } from "next-auth/react";
import router from "next/router";
import { useEffect } from "react";

const Index = () => {
  const { data: session, status } = useSession();
  useEffect(() => {
    if (session) {
      setTimeout(() => {
        router.push("/startsida");
      }, 2000); // Change to the desired duration of the transition
    }
  }, [session]);
  async function handleGoogleSignin() {
    signIn("google", { callbackUrl: "http://localhost:3000" });
  }

  async function handleSignOut() {
    signOut();
  }
  if (status === "loading") {
    return <div className="w-screen h-screen"></div>;
  } else if (session) {
    return (
      <div className="flex justify-center items-center w-screen h-screen">
        <div className="flex-col">
          <p>
            Välkommen tillbaka
            <span className="font-extrabold"> {session.user?.name}</span>
          </p>
          <br />
          <br />
          <div className="flex w-auto">
            <div className="w-3 h-3 bg-active-offWHite rounded-full mr-1 animate-pulse"></div>
            <div className="w-3 h-3 bg-active-offWHite rounded-full mr-1 animate__animated animate__fadeIn animate__delay-2s"></div>
            <div className="w-3 h-3 bg-active-offWHite rounded-full animate__animated animate__fadeIn animate__delay-3s"></div>
          </div>
        </div>
      </div>
    );
  } else
    return (
      <div className=" flex flex-wrap h-screen bg-gradient-to-b from-active-bluelight via-active-purplelight to-active-goldlight">
        <title>Active-log in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icons" href="/Activeicon.ico" />

        <div className="flex justify-center absolute inset-x-0 top-20 mb-10 w-full">
          <Image
            src={"/active-logo-medium.png"}
            alt={"#"}
            width={"176"}
            height={"48"}
          />
        </div>

        <form
          id="loginForm"
          className="bg-white rounded px-24 pt-56 pb-8 mb-4 round"
        >
          <input
            className=" shadow appearance-none border rounded py-2 px-3 text-gray-700  leading-tight focus:outline-none focus:shadow-outline"
            type="text"
            id="username"
            placeholder="Användarnamn..."
          />

          <input
            className=" shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
            type="text"
            id="password"
            placeholder="Lösenord..."
          />
          <Link href="/startsida">Glömt lösenord</Link>

          <div className="flex justify-center items-center mt-8">
            <button
              className=" purple1 hover:bg-purple-700  text-active-offWHite font-bold py-2 px-4 rounded "
              type="button"
              onClick={() => router.push("/startsida")}
            >
              Logga in
            </button>
            <button
              className=" purple1 hover:bg-purple-700  text-active-offWHite font-bold py-2 px-4 rounded "
              type="button"
              onClick={handleGoogleSignin}
            >
              Logga in med google
            </button>
          </div>
        </form>
      </div>
    );
};

export default Index;
