import Image from "next/image";
import Link from "next/link";

const Index = () => {
  return (
    <div className=" flex flex-wrap h-screen bg-gradient-to-b from-active-bluelight via-active-purplelight to-active-goldlight">
      <title>Active-log in</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icons" href="/Activeicon.ico" />

      <div className="flex justify-center absolute inset-x-0 top-20 mb-10 w-full">
        <Image
          src={"/active-logo-medium.png"}
          alt={"#"}
          width={"176"}
          height={"48"}
        />
      </div>

      <form
        id="loginForm"
        className="bg-white rounded px-24 pt-56 pb-8 mb-4 round"
      >
        <input
          className=" shadow appearance-none border rounded py-2 px-3 text-gray-700  leading-tight focus:outline-none focus:shadow-outline"
          type="text"
          id="username"
          placeholder="Användarnamn..."
        />

        <input
          className=" shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
          type="text"
          id="password"
          placeholder="Lösenord..."
        />
        <Link href="/startsida">
          <a>Glömt lösenord</a>
        </Link>

        <div className="flex justify-center items-center mt-8">
          <button
            className=" purple1 hover:bg-purple-700  text-active-offWHite font-bold py-2 px-4 rounded "
            type="button"
          >
            Logga in
          </button>
        </div>
      </form>
    </div>
  );
};

export default Index;
